version: '3.9'

services:
  hello:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello
    ports:
      - '5000:5000'

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
